version: '3.8'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile.dev
        image: next-app
        container_name: next-app
        # env_file:
        #     - .env
        volumes:
            - type: bind
              source: ./src
              target: /src

            - type: volume
              source: node_modules
              target: /src/node_modules

            # - type: public
            #   source: ./src/public
            #   target: /src/public
        # command: ['npm', 'run', 'dev']
        ports:
            - '3007:3000'
        restart: always
        tty: true
        stdin_open: true
        environment:
            # - CHOKIDAR_USEPOLLING=true
            - WATCHPACK_POLLING=true
volumes:
    node_modules:
