version: '3.8'
services:
    base:
        build:
            context: .
            dockerfile: Dockerfile.base
        image: node_base
        volumes:
            - type: bind
              source: ./src
              target: /src
        entrypoint: ['npx', '-y', 'create-next-app', '.']
        command:
            [
                '--tailwind',
                '--ts',
                '--eslint',
                '--app',
                '--no-src-dir',
                '--import-alias',
                '@/*'
            ]
    installer:
        image: node_base
        volumes:
            - type: bind
              source: ./src
              target: /src
        entrypoint: ['npm', 'install']
        command: ['prettier', 'eslint-config-prettier']
